// Code generated by mockery v1.0.0. DO NOT EDIT.

package types

import mock "github.com/stretchr/testify/mock"

// MockTxMgr is an autogenerated mock type for the TxMgr type
type MockTxMgr struct {
	mock.Mock
}

// GetMultiSignersInfo provides a mock function with given fields: txType
func (_m *MockTxMgr) GetMultiSignersInfo(txType SupportType) *SignersInfo {
	ret := _m.Called(txType)

	var r0 *SignersInfo
	if rf, ok := ret.Get(0).(func(SupportType) *SignersInfo); ok {
		r0 = rf(txType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignersInfo)
		}
	}

	return r0
}
