// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import p2p "github.com/lianxiangcloud/linkchain/libs/p2p"

// P2PManager is an autogenerated mock type for the P2PManager type
type P2PManager struct {
	mock.Mock
}

// NumPeers provides a mock function with given fields:
func (_m *P2PManager) NumPeers() (int, int, int) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 int
	if rf, ok := ret.Get(2).(func() int); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}

// Peers provides a mock function with given fields:
func (_m *P2PManager) Peers() p2p.IPeerSet {
	ret := _m.Called()

	var r0 p2p.IPeerSet
	if rf, ok := ret.Get(0).(func() p2p.IPeerSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(p2p.IPeerSet)
		}
	}

	return r0
}
